---
# This is a role for the host attacker.
# You can write your tasks here.
# These changes will affect only the host attacker.

- name: Install common tools
  apt:
    name: [vim, nano, mc, curl]
    state: present
    update_cache: yes

- name: Copy metasploit plugin to the server
  copy:
    src: 47230.rb
    dest: /usr/share/metasploit-framework/modules/exploits/
    owner: root
    group: root
    mode: u=rw,g=rw,o=rw 

- name: install exploitdb
  apt:
    name: exploitdb
    state: present
    update_cache: yes

- name: create /usr/share/wordlists directory
  file:
    path: /usr/share/wordlists
    state: directory
    owner: user
    group: user

- name: Copy wordlists to the machine
  copy:
    src: rockyou.txt
    dest: /usr/share/wordlists
    owner: user
    group: user
    mode: 0666

- name: download ssh2john.py
  get_url:
    url: https://raw.githubusercontent.com/openwall/john/bleeding-jumbo/run/ssh2john.py
    dest: /home/user/ssh2john.py
    owner: user
    group: user
    mode: 0777

...
