---
# This is a role for the host attacker.
# You can write your tasks here.
# These changes will affect only the host attacker.

- name: Install common tools
  apt:
    name: [ vim, nano, mc, curl ]
    state: present
    update_cache: yes

- name: Copy metasploit plugin to the server
  copy:
    src: 47230.rb
    dest: /usr/share/metasploit-framework/modules/exploits/
    owner: root
    group: root
    mode: u=rw,g=rw,o=rw

- name: install exploitdb
  apt:
    name: exploitdb
    state: present
    update_cache: yes

- name: Unarchive rockyou wordlist
  command: gunzip /usr/share/wordlists/rockyou.txt.gz

- name: Remove other wordlists
  file:
    path: "/usr/share/wordlists/{{ item }}"
    state: absent
  with_items:
    - dirb
    - dirbuster
    - fern-wifi
    - metasploit
    - nmap.lst
    - wfuzz
    - fasttrack.txt

- name: download ssh2john.py
  get_url:
    url: https://raw.githubusercontent.com/openwall/john/bleeding-jumbo/run/ssh2john.py
    dest: /home/user/ssh2john.py
    owner: user
    group: user
    mode: '0777'
...
